[tool.poetry]
name = "anki-generator"
version = "0.1.0"
description = ""
authors = ["WillamesCampos <willwjccampos@gmail.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
pymongo = "^4.15.1"
python-dotenv = "^1.1.1"
django = "^6.0"
djangorestframework = "^3.17.1"
psycopg2-binary = "^2.9.12"
celery = "^5.6.3"
redis = "^8.1.0"
djangorestframework-simplejwt = "^5.5.1"
django-allauth = "^65.18.0"
dj-rest-auth = "^7.2.0"
requests = "^2.34.2"
cryptography = "^50.0.0"
fsrs = "^6.3.2"
django-cors-headers = "^4.9.0"


[tool.poetry.group.dev.dependencies]
pytest = "^9.1.1"
pytest-django = "^4.12.0"
black = "^26.5.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.settings.local"
python_files = ["test_*.py", "*_test.py", "tests.py"]

[tool.black]
target-version = ["py313"]
force-exclude = '''
(
    (^|/)manage\.py$
    | /migrations/
)
'''

